packages:
  - packages/*
  - samples/**

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@workleap*'
  - '@typescript/native-preview*'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - protobufjs
