packages:
  - packages/*
  - samples/**

onlyBuiltDependencies:
  - agent-browser
  - core-js
  - edgedriver
  - esbuild
  - geckodriver
  - protobufjs

patchedDependencies:
  logrocket@12.0.0: patches/logrocket@12.0.0.patch
