packages:
  - packages/*
  - samples/**

# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#   - '@workleap*'
#   - '@typescript/native-preview*'

onlyBuiltDependencies:
  - agent-browser
  - core-js
  - esbuild
  - protobufjs
