packages:
  - packages/*
  - samples/**

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@workleap*'
  - '@typescript/native-preview'
  - '@typescript/native-preview-win32-x64'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - protobufjs
